#
# Travis defaults to building on Ubuntu Precise. We need Trusty
# in order to get up to date versions of cmake and g++
#
language: cpp
sudo: required
dist: trusty

#
# The addon source is automatically checked out in $TRAVIS_BUILD_DIR,
# we'll put the Kodi source on the same level
#
before_script:
  - cd $TRAVIS_BUILD_DIR/..

  - # Building and installing KissFFT
  - git clone --depth=1 https://github.com/Tadly/KissFFT.git
  - cd KissFFT && mkdir -p build && cd build
  - cmake ../ && sudo make install && cd ../../

  - # Building and installing asplib
  - git clone --depth=1 https://github.com/AchimTuran/asplib -b add-spectrum-vis-processor
  - cd asplib && mkdir -p build && cd build
  - cmake ../ && sudo make install && cd ../../

  - # Building and installing PictureIt
  - git clone --depth=1 https://github.com/linuxwhatelse/PictureIt.git
  - cd PictureIt && mkdir -p build && cd build
  - cmake ../ && sudo make install && cd ../../

  - # Building visualization.pictureit
  - git clone --depth=1 https://github.com/linuxwhatelse/xbmc.git
  - cd visualization.pictureit && mkdir -p build && cd build
  - cmake -DADDONS_TO_BUILD=visualization.pictureit -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/project/cmake/addons

script: make
